jwunderl/pxt-arcade

docs/courses/javascript/orientation.md
docs/courses/javascript/orientation/case-study.md

Resolves #95 
Adding in case study game
(Currently saved game is 'full game' in progress; will need to move to separate location and trim for students before merging)

Add Case Study

---

docs/courses/csintro3/orientation/types.md

Changed ||string:*|| to ||text:*||

---

docs/courses/csintro3/orientation/loops.md

Fill in orientation/loops

---

docs/courses/csintro3/orientation/math.md

Filled out the orientation/math page for JavaScript
As per #76

added math

---

docs/courses/csintro3/orientation/types-problems.md
docs/courses/csintro3/orientation/types.md

Material for types problem set re: #98

Types problem set

---

docs/courses/csintro3/orientation.md
docs/courses/csintro3/orientation/user-input.md

closes #120 
The example for task 3 seems useful but is real long to display, will cut it down or something

fill out orientation/user-input

---

docs/courses/csintro3/functions/parameters.md
docs/courses/csintro3/functions/returns.md

Filled out functions/parameters and functions/returns
#86 and #87

Functions/Parameters and Functions/Returns

---

docs/courses/csintro3/functions/intro.md

Function lesson intro

---

docs/courses/csintro3/functions/optional.md

Add this to appendix section
#88

Filled out functions/optional #88

---

docs/courses/csintro3/orientation/logic-problems.md

Filled out problem set for logic
#98

Added Logic Problem Set

---

docs/courses/csintro3/orientation/loops-problems.md

Filled out Loops Problem set
#98

Added loops Problem Set 

---

docs/courses/csintro3/orientation/extensions-problems.md

Added extensions problems

---

docs/courses/csintro3/events/info.md

events info lesson

---

docs/courses/csintro3/orientation/namespaces-problems.md

Added problem set for namespaces

---

docs/courses/csintro3/orientation/namespaces-problems.md

edits for namespaces problem set

---

docs/courses/csintro3/events/buttons.md

Filled out button event lesson

---

docs/courses/csintro3/arrays/numbers.md
docs/courses/csintro3/events/update.md

I need to reread / edit this still
closes #94

number arrays lesson

---

docs/courses/csintro3.md
docs/courses/csintro3/SUMMARY.md
docs/courses/csintro3/arrays.md
docs/courses/csintro3/arrays/strings.md

Closes #92 
last concept probably Math.pickRandom

Arrays strings / modification lesson

---

docs/courses/csintro3/arrays/sprites.md

closes #93 
(in progress, just adding because I committed a few lines before trying to debug broken build)

sprites arrays lesson

---

docs/courses/csintro3/about/style.md
docs/courses/csintro3/intro/initialization.md

closes #125
need a few run throughs / reviews to make sure we cover most things in it, very easy to skim over something in a style guide

style guide

---

docs/courses/csintro3/about/start.md
docs/courses/csintro3/intro/initialization.md

'where to start' page

---

docs/courses/csintro3/appendix/switch.md

appendix for switch case closes #132

Switch case appendix

---

docs/courses/csintro3/appendix/for-each.md

closes #158
also has a quick discussion of arrow functions as an extra side note appendix

for each appendix

---

docs/courses/csintro3/intro/initialization.md
docs/courses/csintro3/intro/math.md
docs/courses/csintro3/intro/operators.md
docs/courses/csintro3/intro/types.md
docs/courses/csintro3/intro/user-input.md
docs/courses/csintro3/structure/extensions.md
docs/courses/csintro3/structure/logic-problems.md
docs/courses/csintro3/structure/logic.md
docs/courses/csintro3/structure/loops.md
docs/courses/csintro3/structure/namespaces.md
docs/courses/csintro3/structure/sprites.md
docs/courses/csintro3/structure/tilemaps-problems.md
docs/courses/csintro3/structure/tilemaps.md

Links to problems pages for intro and structure

---

docs/courses/csintro3/appendix/nested-functions.md

Appendix: nested functions

---

docs/courses/csintro3/arrays/sprites.md
docs/courses/csintro3/arrays/strings.md
docs/courses/csintro3/arrays/tiles.md
docs/courses/csintro3/events/buttons.md
docs/courses/csintro3/events/info.md
docs/courses/csintro3/events/overlap.md
docs/courses/csintro3/intro/case-study.md
docs/courses/csintro3/structure/sprites.md
docs/courses/csintro3/structure/tilemaps.md

control->move sprite fixes across lessons

---

docs/courses/csintro3/arrays/numbers-problems.md
docs/courses/csintro3/arrays/numbers.md
docs/courses/csintro3/arrays/sprites-problems.md
docs/courses/csintro3/arrays/sprites.md
docs/courses/csintro3/arrays/strings-problems.md
docs/courses/csintro3/arrays/strings.md

Arrays problem sets (numbers/strings/sprites)

---

docs/courses/csintro3/arrays/images-problems.md
docs/courses/csintro3/arrays/images.md
docs/courses/csintro3/arrays/tiles-problems.md

Rest of array problem sets

---

docs/courses/csintro3/events/buttons.md
docs/courses/csintro3/events/case-study.md
docs/courses/csintro3/events/info.md
docs/courses/csintro3/events/intro.md
docs/courses/csintro3/events/overlap.md
docs/courses/csintro3/events/update.md
docs/courses/csintro3/functions/case-study.md

Case study for events section

---

docs/courses/csintro3/arrays/case-study.md
docs/courses/csintro3/arrays/images.md
docs/courses/csintro3/arrays/numbers.md
docs/courses/csintro3/arrays/sprites.md
docs/courses/csintro3/arrays/strings.md
docs/courses/csintro3/arrays/tiles.md
docs/courses/csintro3/events/case-study.md
docs/courses/csintro3/events/info.md
docs/courses/csintro3/events/intro.md
docs/courses/csintro3/events/overlap.md
docs/courses/csintro3/events/update.md
docs/courses/csintro3/functions/case-study.md
docs/courses/csintro3/functions/comments.md
docs/courses/csintro3/structure/additions.md

arrays case study sections

---

docs/courses/csintro3/functions/comments-problems.md

Filled out problem set for function comments

---

docs/courses/csintro3/functions/parameters-problems.md
docs/courses/csintro3/functions/returns-problems.md

Filled out function parameters and returns problems

---

docs/courses/csintro3/functions/comments-problems.md

comments problems edits

---

docs/courses/csintro3/functions/comments-problems.md
docs/courses/csintro3/functions/parameters-problems.md
docs/courses/csintro3/functions/returns-problems.md

edits for returns and parameters problemsets

---

docs/courses/csintro3/arrays/images.md
docs/courses/csintro3/arrays/numbers.md
docs/courses/csintro3/arrays/sprites.md
docs/courses/csintro3/arrays/strings.md
docs/courses/csintro3/arrays/tiles.md
docs/courses/csintro3/events/buttons.md
docs/courses/csintro3/events/info.md
docs/courses/csintro3/events/intro.md
docs/courses/csintro3/events/overlap.md
docs/courses/csintro3/events/update.md
docs/courses/csintro3/functions/comments.md
docs/courses/csintro3/functions/intro.md
docs/courses/csintro3/functions/parameters.md
docs/courses/csintro3/functions/returns.md

links to problem sets
